// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuSporKiralama.DataAccess;

#nullable disable

namespace SuSporKiralama.DataAccess.Migrations
{
    [DbContext(typeof(SuSporKiralamaDbContext))]
    [Migration("20260930203224_KiralamaDepozitoTakibi")]
    partial class KiralamaDepozitoTakibi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuSporKiralama.Entities.HasarKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("HasarBedeli")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KiralamaDetayId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KiralamaDetayId");

                    b.ToTable("HasarKayitlari", (string)null);
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Kiralama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepozitoDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DepozitoMahsupTutari")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DepozitoTutari")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("GercekBitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlanlananBitisZamani")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ToplamUcret")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("Durum", "BaslangicZamani");

                    b.ToTable("Kiralamalar", (string)null);
                });

            modelBuilder.Entity("SuSporKiralama.Entities.KiralamaDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EkipmanId")
                        .HasColumnType("int");

                    b.Property<decimal?>("HesaplananUcret")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("KiralamaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UygulananBirimUcret")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EkipmanId");

                    b.HasIndex("KiralamaId", "EkipmanId")
                        .IsUnique();

                    b.ToTable("KiralamaDetaylari", (string)null);
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("DeneyimSeviyesi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notlar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Telefon")
                        .IsUnique();

                    b.ToTable("Musteriler", (string)null);
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Odeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("KiralamaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("KiralamaId");

                    b.ToTable("Odemeler", (string)null);
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Soyut.Ekipman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimUcret")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("DepozitoTutari")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EkipmanTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Ekipmanlar", (string)null);

                    b.HasDiscriminator<string>("EkipmanTipi").HasValue("Ekipman");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SuSporKiralama.Entities.CanYelegi", b =>
                {
                    b.HasBaseType("SuSporKiralama.Entities.Soyut.Ekipman");

                    b.Property<string>("Beden")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("CanYelegi");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Kano", b =>
                {
                    b.HasBaseType("SuSporKiralama.Entities.Soyut.Ekipman");

                    b.Property<int>("KisiKapasitesi")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Kano");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.SupBoard", b =>
                {
                    b.HasBaseType("SuSporKiralama.Entities.Soyut.Ekipman");

                    b.Property<int>("MaxTasimaKg")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UzunlukCm")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("SupBoard");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.HasarKaydi", b =>
                {
                    b.HasOne("SuSporKiralama.Entities.KiralamaDetay", "KiralamaDetay")
                        .WithMany("HasarKayitlari")
                        .HasForeignKey("KiralamaDetayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KiralamaDetay");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Kiralama", b =>
                {
                    b.HasOne("SuSporKiralama.Entities.Musteri", "Musteri")
                        .WithMany("Kiralamalar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuSporKiralama.Entities.Personel", "Personel")
                        .WithMany("Kiralamalar")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.KiralamaDetay", b =>
                {
                    b.HasOne("SuSporKiralama.Entities.Soyut.Ekipman", "Ekipman")
                        .WithMany("KiralamaDetaylari")
                        .HasForeignKey("EkipmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuSporKiralama.Entities.Kiralama", "Kiralama")
                        .WithMany("Detaylar")
                        .HasForeignKey("KiralamaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ekipman");

                    b.Navigation("Kiralama");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Odeme", b =>
                {
                    b.HasOne("SuSporKiralama.Entities.Kiralama", "Kiralama")
                        .WithMany("Odemeler")
                        .HasForeignKey("KiralamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kiralama");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Kiralama", b =>
                {
                    b.Navigation("Detaylar");

                    b.Navigation("Odemeler");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.KiralamaDetay", b =>
                {
                    b.Navigation("HasarKayitlari");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Musteri", b =>
                {
                    b.Navigation("Kiralamalar");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Personel", b =>
                {
                    b.Navigation("Kiralamalar");
                });

            modelBuilder.Entity("SuSporKiralama.Entities.Soyut.Ekipman", b =>
                {
                    b.Navigation("KiralamaDetaylari");
                });
#pragma warning restore 612, 618
        }
    }
}
